# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

plugins: [jekyll-paginate]

# Site settings
title: NewHaven.IO
description: > # this means to ignore newlines until "baseurl:"
  NewHaven.IO is a group of talented and passionate programmers living, working and creating in the New Haven area.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://newhaven.io" # the base hostname & protocol for your site
permalink: /blog/:title/
paginate: 9,
paginate_path: "/blog/page:num/"

exclude: [
  'node_modules'
]
sass:
  style: compressed

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-42537303-1
